apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: '{{ .Release.Namespace }}'

resources:
  - input/deployment-rbac.yaml
  - input/mic-exception.yaml

images:
  - name: mcr.microsoft.com/oss/azure/aad-pod-identity/mic:*
    newName: "{{ .Values.image.registry }}/{{ .Values.mic.image.name }}"
    newTag: "{{ .Values.mic.image.tag}}"

transformers:
  - transformers/common-labels.yaml
  - transformers/deployment-labels.yaml

patchesStrategicMerge:
  - patches/nmi-daemonset.yaml

patches:
- path: patches/deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
- path: patches/mic-clusterrole.yaml
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: aad-pod-id-mic-role

