{{- if .Values.rbac.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "aad.crdInstall" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "aad.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
spec:
  allowPrivilegeEscalation: true
  privileged: true
  allowedCapabilities:
    - DAC_READ_SEARCH
    - NET_ADMIN
    - NET_RAW
  volumes:
    - 'configMap'
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/run/xtables.lock"
    - pathPrefix: "{{ .Values.nmi.kubeletConfig }}"
  requiredDropCapabilities:
  - ALL
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}

