{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "files/**.yaml" }}
    {{- with $currentScope }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aad.crdInstall" . }}-{{ printf "%s-%s" (base (dir $path)) (trimSuffix ".yaml" (base $path) | trunc 63) }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "aad.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "aad.crdInstall" . | quote }}
    {{- include "aad.selectorLabels" . | nindent 4 }}
    role: {{ include "aad.CRDInstallSelector" . | quote }}
data:
  content: |
{{ tpl ($.Files.Get $path) . | indent 4 }}
    {{- end }}
  {{- end }}
