version: 2.1
orbs:
  architect: giantswarm/architect@2.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push azure-ad-pod-identity-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "azure-ad-pod-identity-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "azure-ad-pod-identity-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
