apiVersion: v1
appVersion: 1.6.1
description: Deploy components for the azure-ad-pod-identity-app
name: azure-ad-pod-identity-app
namespace: kube-system
version: [[ .Version ]]
home: https://github.com/giantswarm/azure-ad-pod-identity-app
sources:
  - https://raw.githubusercontent.com/cloudworkz/kube-eagle-helm-chart/master/README.md
  - https://raw.githubusercontent.com/giantswarm/azure-ad-pod-identity-app/v[[ .Version ]]/README.md
icon: https://s.giantswarm.io/app-icons/1/png/azure-ad-pod-identity-app-light.png
