# Default values for azure-ad-pod-identity-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override aad-pod-identity.fullname template with a string (will prepend the release name)
nameOverride: ""
# String to fully override aad-pod-identity.fullname template with a string
fullnameOverride: ""

image:
  # Image registry
  registry: quay.io
  # Image pull policy
  imagePullPolicy: Always

# https://github.com/Azure/aad-pod-identity#4-optional-match-pods-in-the-namespace
# By default, AAD Pod Identity matches pods to identities across namespaces.
# To match only pods in the namespace containing AzureIdentity set this to true.
forceNameSpaced: false

# When NMI runs on a node where MIC is running, then MIC token request call is also
# intercepted by NMI. MIC can't get a valid token as to initialize and then
# assign the identity. Installing an exception for MIC would ensure all token requests
# for MIC pods directly go to IMDS and not go through the pod-identity validation
# https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.app-exception.md
installMICException: "true"

## If using a separate service principal for aad-pod-identity instead of cluster service principal specify the following
## (The chart will perform the base64 encoding for you for values that are stored in secrets.)
adminsecret:
  # Azure cloud environment name. Should be one of: AzurePublicCloud, AzureUSGovernmentCloud, AzureChinaCloud, AzureGermanCloud
  cloud: ""
  # Azure subscription ID where the cluster is located
  subscriptionID: ""
  # Azure resource group of the cluster
  resourceGroup: ""
  # vmType: <`standard` for normal virtual machine nodes, and `vmss` for cluster deployed with a virtual machine scale set>
  vmType: "vmss"
  # Azure service principal tenantID
  tenantID: ""
  # Azure service principal clientID
  clientID: ""
  # Azure service principal clientSecret
  clientSecret: ""

# Operation mode for pod-identity. Default is standard mode that has MIC doing identity assignment
# Allowed values: "standard", "managed"
operationMode: "standard"

kubelet:
  path: /opt/bin/kubelet

mic:
  image:
    name: giantswarm/mic
    tag: 1.7.4

  priorityClassName: ""

  # log level. Uses V logs (glog)
  logVerbosity: 0

  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

  podAnnotations: {}

  ## Node labels for pod assignment
  ## aad-pod-identity is currently only supported on linux
  nodeSelector:
    kubernetes.io/os: linux

  tolerations: []

  affinity: {}

  leaderElection:
    # Override leader election instance name (default is 'hostname')
    instance: ""
    # Override leader election name (default is aad-pod-identity-mic)
    name: ""
    # Override leader election duration (default is 15s)
    duration: ""

  # Override http liveliness probe port (default is 8080)
  probePort: ""

  # Override interval in seconds at which sync loop should periodically check for errors and reconcile (default is 3600s)
  syncRetryDuration: ""

  # Override the defult value of immutable identities.
  immutableUserMSIs: []
    # Example of MSIs (should be replaced with the real client ids)
    # - "00000000-0000-0000-0000-000000000000"
    # - "11111111-1111-1111-1111-111111111111"

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#batch-create-delete-flag
  # default value is 20
  createDeleteBatch: ""

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#client-qps-flag
  # default value is 5
  clientQps: ""

  # prometheus port for metrics (default is 8888)
  prometheusPort: "8888"

  # The maximum retry of UpdateUserMSI call. MIC updates all the identities in a batch. If a single identity contains an error
  # or is invalid, then the entire operation fails. Configuring this flag will make MIC retry by removing the erroneous identities
  # returned in the error
  # Default value is 2.
  updateUserMSIMaxRetry: ""

  # The duration to wait before retrying UpdateUserMSI (batch assigning/un-assigning identity from VM/VMSS) in case of errors
  # Default value is 1s
  updateUserMSIRetryInterval: ""

nmi:
  image:
    name: giantswarm/nmi
    tag: 1.7.4

  priorityClassName: ""

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  podAnnotations: {}

  ## Node labels for pod assignment
  ## aad-pod-identity is currently only supported on linux
  nodeSelector:
    kubernetes.io/os: linux

  # List of node taints to tolerate
  tolerations: []

  # Affinity settings
  affinity: {}

  # Override iptables update interval in seconds (default is 60)
  ipTableUpdateTimeIntervalInSeconds: "60"

  # Override http liveliness probe port (default is 8080)
  probePort: "8080"

  # Override number of retries in NMI to find assigned identity in CREATED state (default is 16)
  retryAttemptsForCreated: "16"

  # Override number of retries in NMI to find assigned identity in ASSIGNED state (default is 4)
  retryAttemptsForAssigned: "4"

  # Override retry interval to find assigned identities in seconds (default is 5)
  findIdentityRetryIntervalInSeconds: "5"

  # Enable scale features - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#enable-scale-features-flag (default is false)
  enableScaleFeatures: "false"

  # prometheus port for metrics (default is 9090)
  prometheusPort: "9090"

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#block-instance-metadata-flag (default is false)
  blockInstanceMetadata: "false"

  # https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.featureflags.md#metadata-header-required-flag (default is false)
  metadataHeaderRequired: "false"

rbac:
  enabled: true
  # NMI requires permissions to get secrets when service principal (type: 1) is used in AzureIdentity.
  # If using only MSI (type: 0) in AzureIdentity, secret get permission can be disabled by setting this to false.
  allowAccessToSecrets: true

# Create azure identities and bindings
azureIdentities: []
  # - name: "azure-identity"
  #   # if not defined, then the azure identity will be deployed in the same namespace as the chart
  #   namespace: ""
  #   # type 0: MSI, type 1: Service Principal
  #   type: 0
  #   # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  #   resourceID: ""
  #   clientID: ""
  #   binding:
  #     name: "azure-identity-binding"
  #     # The selector will also need to be included in labels for app deployment
  #     selector: "demo"

# If true, install necessary custom resources.
installCRDs: false
