---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: '{{ .Chart.Name }}'
  app.kubernetes.io/name: '{{ template "aad-pod-identity.name" . }}'
  app.kubernetes.io/instance: '{{ .Release.Name }}'
  application.giantswarm.io/team: "phoenix"

fieldSpecs:
  - path: metadata/labels
    create: true
