{{- range $exception := .Values.exceptions }}
{{- if and (gt (len $exception.namespaces) 0) (gt (len (keys $exception.podLabels)) 0) }}
{{- range $exception.namespaces }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: {{ if $exception.name }}{{ $exception.name }}{{ else }}ad-id-exc-{{ . }}{{ end }}
  namespace: {{ . }}
spec:
  podLabels:
    {{- range $k, $v := $exception.podLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
