{{- if and .Values.rbac.enabled (eq .Values.operationMode "standard") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
{{- end }}
