{{- if eq .Values.operationMode "standard" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: mic
spec:
  selector:
    {{- include "aad-pod-identity.selectors" . | nindent 4 }}
    app.kubernetes.io/component: mic
  clusterIP: "None"
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.mic.prometheusPort }}
      targetPort: {{ .Values.mic.prometheusPort }}
{{- end }}
