{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: nmi
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: {{ template "aad-pod-identity.nmi.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
