apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    description: {{ .Chart.Description }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "aad-pod-identity.selectors" . | nindent 6 }}
      app.kubernetes.io/component: nmi
  template:
    metadata:
      labels:
        {{- include "aad-pod-identity.labels" . | nindent 8 }}
        app.kubernetes.io/component: nmi
{{- if .Values.nmi.podAnnotations }}
      annotations:
{{ toYaml .Values.nmi.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "aad-pod-identity.nmi.fullname" . }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.nmi.priorityClassName }}
      priorityClassName: {{ .Values.nmi.priorityClassName | quote }}
      {{- end }}
      volumes:
      - name: iptableslock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      {{- if semverCompare ">= 1.7.0-0" .Values.nmi.image.tag }}
      - name: kubelet-config
        hostPath:
          path: {{ .Values.nmi.kubeletConfig }}
      {{- end }}
      containers:
      - name: nmi
        image: "{{ .Values.image.registry }}/{{ .Values.nmi.image.name }}:{{ .Values.nmi.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        args:
          {{- if semverCompare "<= 1.6.1-0" .Values.nmi.image.tag }}
          - "--host-ip=$(HOST_IP)"
          {{- end }}
          - "--node=$(NODE_NAME)"
          {{- if .Values.nmi.probePort }}
          - --http-probe-port={{ .Values.nmi.probePort }}
          {{- end }}
          {{- if .Values.nmi.ipTableUpdateTimeIntervalInSeconds }}
          - --ipt-update-interval-sec={{ .Values.nmi.ipTableUpdateTimeIntervalInSeconds }}
          {{- end }}
          {{- if .Values.nmi.micNamespace }}
          - --MICNamespace={{ .Values.nmi.micNamespace }}
          {{- end }}
          {{- if .Values.nmi.retryAttemptsForCreated }}
          - --retry-attempts-for-created={{ .Values.nmi.retryAttemptsForCreated }}
          {{- end }}
          {{- if .Values.nmi.retryAttemptsForAssigned }}
          - --retry-attempts-for-assigned={{ .Values.nmi.retryAttemptsForAssigned }}
          {{- end }}
          {{- if .Values.nmi.findIdentityRetryIntervalInSeconds }}
          - --find-identity-retry-interval={{ .Values.nmi.findIdentityRetryIntervalInSeconds }}
          {{- end }}
          {{- if .Values.nmi.enableScaleFeatures }}
          - --enableScaleFeatures={{ .Values.nmi.enableScaleFeatures }}
          {{- end }}
          {{- if .Values.nmi.prometheusPort }}
          - --prometheus-port={{ .Values.nmi.prometheusPort }}
          {{- end }}
          {{- if .Values.nmi.blockInstanceMetadata }}
          - --block-instance-metadata={{ .Values.nmi.blockInstanceMetadata }}
          {{- end }}
          - --metadata-header-required={{ .Values.nmi.metadataHeaderRequired }}
          {{- if .Values.nmi.loggingFormat }}
          - --log-format={{ .Values.nmi.loggingFormat }}
          {{- end}}
          {{- if .Values.nmi.logVerbosity }}
          - -v={{ .Values.nmi.logVerbosity }}
          {{- end }}
          {{- if semverCompare ">= 1.6.0-0" .Values.nmi.image.tag }}
          - --operation-mode={{ .Values.operationMode }}
          {{- end}}
          {{- if eq .Values.operationMode "managed" }}
          - --forceNamespaced
          {{- end }}
          {{- if .Values.nmi.allowNetworkPluginKubenet }}
          - --allow-network-plugin-kubenet={{ .Values.nmi.allowNetworkPluginKubenet }}
          {{- end }}
          {{- if semverCompare ">= 1.7.0-0" .Values.nmi.image.tag }}
          - --kubelet-config={{ .Values.nmi.kubeletConfig }}
          {{- end }}
          {{- if .Values.customUserAgent }}
          - --custom-user-agent={{ .Values.customUserAgent }}
          {{- end }}
          {{- if .Values.nmi.listenAddress }}
          - --nmi-listen-address={{ .Values.nmi.listenAddress }}
          {{- end }}
        env:
        {{- if semverCompare "<= 1.6.1-0" .Values.nmi.image.tag }}
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- end }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if eq .Values.operationMode "standard" }}
        - name: FORCENAMESPACED
          value: "{{ .Values.forceNamespaced }}"
        {{- end }}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsUser: 0
          capabilities:
            drop:
            - ALL
            add:
            - DAC_READ_SEARCH
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - name: iptableslock
          mountPath: /run/xtables.lock
        {{- if semverCompare ">= 1.7.0-0" .Values.nmi.image.tag }}
        - name: kubelet-config
          mountPath: {{ .Values.nmi.kubeletConfig }}
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.nmi.probePort | default 8080 }}
          initialDelaySeconds: 10
          periodSeconds: 5
{{- with .Values.nmi.resources }}
        resources:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.nmi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nmi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nmi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
