apiVersion: v1
kind: Service
metadata:
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
spec:
  selector:
    {{- include "aad-pod-identity.selectors" . | nindent 4 }}
    app.kubernetes.io/component: nmi
  clusterIP: "None"
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.nmi.prometheusPort }}
    targetPort: {{ .Values.nmi.prometheusPort }}
