{{- if .Values.rbac.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
spec:
  allowPrivilegeEscalation: true
  privileged: true
  allowedCapabilities:
    - "NET_ADMIN"
  volumes:
    - 'configMap'
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/run/xtables.lock"
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}