apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    description: {{ .Chart.Description }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "aad-pod-identity.selectors" . | nindent 6 }}
      app.kubernetes.io/component: nmi
  template:
    metadata:
      labels:
        {{- include "aad-pod-identity.labels" . | nindent 8 }}
        app.kubernetes.io/component: nmi
{{- if .Values.nmi.podAnnotations }}
      annotations:
{{ toYaml .Values.nmi.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "aad-pod-identity.nmi.fullname" . }}
      {{- end }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.nmi.priorityClassName }}
      priorityClassName: {{ .Values.nmi.priorityClassName | quote }}
      {{- end }}
      volumes:
      - name: iptableslock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate 
      - name: kubelet-config
        hostPath:
          path: {{ .Values.kubelet.path }}
      containers:
      - name: nmi
        image: "{{ .Values.image.registry }}/{{ .Values.nmi.image.name }}:{{ .Values.nmi.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        args:
          - "--host-ip=$(HOST_IP)"
          - "--node=$(NODE_NAME)"
          - --http-probe-port={{ .Values.nmi.probePort | default 8080 }}
          - --operation-mode={{ .Values.operationMode }}
          {{- if eq .Values.operationMode "managed" }}
          - --forceNamespaced
          {{- else }}
          - --MICNamespace={{ .Release.Namespace }}
          {{- end }}
          {{- if .Values.nmi.ipTableUpdateTimeIntervalInSeconds }}
          - --ipt-update-interval-sec={{ .Values.nmi.ipTableUpdateTimeIntervalInSeconds }}
          {{- end }}
          {{- if .Values.nmi.retryAttemptsForCreated }}
          - --retry-attempts-for-created={{ .Values.nmi.retryAttemptsForCreated }}
          {{- end }}
          {{- if .Values.nmi.retryAttemptsForAssigned }}
          - --retry-attempts-for-assigned={{ .Values.nmi.retryAttemptsForAssigned }}
          {{- end }}
          {{- if .Values.nmi.findIdentityRetryIntervalInSeconds }}
          - --find-identity-retry-interval={{ .Values.nmi.findIdentityRetryIntervalInSeconds }}
          {{- end }}
          {{- if .Values.nmi.enableScaleFeatures }}
          - --enableScaleFeatures={{ .Values.nmi.enableScaleFeatures }}
          {{- end }}
          {{- if .Values.nmi.prometheusPort }}
          - --prometheus-port={{ .Values.nmi.prometheusPort }}
          {{- end }}
          {{- if .Values.nmi.blockInstanceMetadata }}
          - --block-instance-metadata={{ .Values.nmi.blockInstanceMetadata }}
          {{- end }}
          {{- if .Values.nmi.metadataHeaderRequired}}
          - --metadata-header-required={{ .Values.nmi.metadataHeaderRequired }}
          {{- end }}
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FORCENAMESPACED
            {{- if eq .Values.operationMode "managed" }}
            value: "true"  
            {{- else }}
            value: "{{ .Values.forceNameSpaced }}"
            {{- end }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: iptableslock
          mountPath: /run/xtables.lock
        - name: kubelet-config
          mountPath: {{ .Values.kubelet.path }}
          readOnly: true  
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.nmi.probePort | default 8080 }}
          initialDelaySeconds: 10
          periodSeconds: 5
{{- with .Values.nmi.resources }}
        resources:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.nmi.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nmi.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nmi.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
