apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "aad-pod-identity.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: phoenix
    helm.sh/chart: '{{ .Chart.Name }}'
    k8s-app: aad-pod-id-nmi-binding
  name: aad-pod-id-nmi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aad-pod-id-nmi-role
subjects:
- kind: ServiceAccount
  name: aad-pod-id-nmi-service-account
  namespace: '{{ .Release.Namespace }}'
