apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "aad-pod-identity.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: phoenix
    helm.sh/chart: '{{ .Chart.Name }}'
  name: aad-pod-id-mic-service-account
  namespace: '{{ .Release.Namespace }}'
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: '{{ template "aad-pod-identity.name" . }}'
        application.giantswarm.io/team: phoenix
